### ISSUE TITLE
Concavity parameter doesn't work

### ISSUE THREAD

**Issue by Bybeez** [AndriiHeonia/hull#14]
I tried using Hull.js with a little over 1000 points, and tried setting the concavity parameter to different values but I get the same results each time and the area is not concave as it should.

**Comment by Bybeez** [comment]
I read a bit of the code and understood my problem, as I was using gps coordinates setting the concavity parameter to 20 or even 1 was too much. I think I'll do a merge request with some modification of the readme so it's clearer.

**Comment by AndriiHeonia** [comment]
closed, as the problem seems to be solved

**Comment by casvanluijtelaar** [comment]
I'm running into the exact same issue. I'm using gps coordinates and I need to create a convex hull with some sort of granularity parameter. but the concavity parameter doesn't seem to work, @Bybeez how did you resolve this?
