### ISSUE TITLE
When will the auto concavity be implemented?

### ISSUE THREAD

**Issue by TheCrowd** [AndriiHeonia/hull#17]
is the auto concavity feature planned in the near future release?

**Comment by AndriiHeonia** [comment]
Hey, that's more like a "nice to have" feature, and it requires some investigation and experiments. Currently, I don't have any particular deadline for that.

**Comment by TheCrowd** [comment]
Hey, thanks for the reply. BTW, do you hava any idea on how to mannually or programatically set the concavity value to have a nice shape?
