### ISSUE TITLE
:bug: No formatting in case there are less than 4 point 

### ISSUE THREAD

**Issue by WBorsych** [AndriiHeonia/hull#22]
Call like

`hull(coords, defaultConcavity, ['.lng', '.lat']);`

will result in array of array tuples if you have less than 4 points in your points `coords` array and not being formatted into objects. Means, the result is unexpected.

Expected:` [ { lng: 1, lat: 1}, { lng: 1, lat: 1}, { lng: 1, lat: 1}, { lng: 1, lat: 1} ]`
Actual:  `[ [1,1], [1,1], [1,1], [1,1]]`

**Comment by AndriiHeonia** [comment]
Thanks for the bug report. I fixed it and released a new version of the library.
