### ISSUE TITLE
C++ port

### ISSUE THREAD

**Issue by pjimenezmateo** [AndriiHeonia/hull#23]
Hi Andrii,

first of all, awesome job, this library is fantastic. I needed it on cpp so I just [ported it](https://github.com/pablojimenezmateo/hulljscpp) and I wanted you to know, let me know if I messed up with the license as I clearly want to give you attribution.

Thanks!

**Comment by AndriiHeonia** [comment]
Hello Pablo, thanks for informing me and thanks for porting the library. The license looks good, no worries.
