### ISSUE TITLE
innerPoints calculation error

### ISSUE THREAD

**Issue by precisionterrain** [AndriiHeonia/hull#4]
Hi,

please note that the below code does not filter duplicate points as expected.

```javascript
 innerPoints = pointset.filter(function (pt) {
    return convex.indexOf(pt) < 0;
});
```

In your main 'How it works' example the point [124,210] is duplicated in the input data set. It exists in both the pointset and convex arrays. Only one of the duplicates is filtered by the above code. Hence inner points still contains this point after the filter is complete.

Not elegant, but the below replacement code would fix.

```javascript
var innerPoints = [];
for (var i = 0; i < pointset.length; i++) {
    var duplicate = false;
    for (var j = 0; j < convex.length; j++) {
        if (convex[j][0] === pointset[i][0] && convex[j][1] === pointset[i][1]) {
            duplicate = true;
            break;
        }
    }
    if (!duplicate) innerPoints.push(pointset[i]);
}
```

**Comment by AndriiHeonia** [comment]
Hi,
thanks for the bug report and sorry for delay with response. I just fixed it and published new version (0.2.9).
