### ISSUE TITLE
Incorrect hull

### ISSUE THREAD

**Issue by MaximPetrichuk** [AndriiHeonia/hull#6]
Hi!
Nice lib, but build incorrect hull with my data. For example:
Points: 
[{"ID":2002000186,"NAME":"098-04","X":25981.376,"Y":11051.213,"TIP":4},{"ID":31561,"NAME":"100-05","X":25761.408,"Y":11046.881,"TIP":4},{"ID":31563,"NAME":"100-06","X":25732.067,"Y":11004.886,"TIP":4},{"ID":31565,"NAME":"100-07","X":25717.202,"Y":10959.749,"TIP":4},{"ID":31567,"NAME":"100-08","X":25697.616,"Y":10908.957,"TIP":4},{"ID":31569,"NAME":"100-09","X":25671.435,"Y":10870.342,"TIP":4},{"ID":31571,"NAME":"100-10","X":25650.06,"Y":10826.486,"TIP":4},{"ID":31573,"NAME":"100-11","X":25626.154,"Y":10777.455,"TIP":4},{"ID":31593,"NAME":"102-07","X":25515.503,"Y":11001.201,"TIP":4},{"ID":31595,"NAME":"102-08","X":25490.95,"Y":10954.007,"TIP":4},{"ID":31597,"NAME":"102-09","X":25468.686,"Y":10907.581,"TIP":4},{"ID":31599,"NAME":"102-10","X":25450.669,"Y":10861.13,"TIP":4},{"ID":31601,"NAME":"102-11","X":25422.485,"Y":10819.644,"TIP":4}]

Build width: hull(arrPoints, Infinity);

Result:
<img width="161" alt="error_hull" src="https://cloud.githubusercontent.com/assets/20028214/21451630/a45b606e-c92a-11e6-865a-dd7cb8a4b092.png">

**Comment by AndriiHeonia** [comment]
Hi,
could you please create jsbin/jsfiddle example? I tried to reproduce this bug with your data and here is how result looks like:
![bug](https://cloud.githubusercontent.com/assets/773648/21471841/414855a8-cac0-11e6-968c-1256df42eedf.png)
This is my code: http://jsbin.com/gogecufesi/edit?html,output

**Comment by MaximPetrichuk** [comment]
Cut a piece of code from project (and add other group of points):
https://jsfiddle.net/Petrichuk/pjpbnj5h/

**Comment by AndriiHeonia** [comment]
Well, you don't pass all your points into the hull() function. Just change

    for (var i = 0; i < pointset.length-1; i++) {
        arrPoints.push([pointset[i].X, pointset[i].Y]);
    };

to

    for (var i = 0; i < pointset.length; i++) {
        arrPoints.push([pointset[i].X, pointset[i].Y]);
    };

and result will be like this:
![bug1](https://cloud.githubusercontent.com/assets/773648/21482073/761e3860-cb6f-11e6-8ced-ace623265ec4.png)

**Comment by MaximPetrichuk** [comment]
Upps, stupid error... 
Thanks and sorry!

**Comment by AndriiHeonia** [comment]
You are welcome. No problem.
