### ISSUE TITLE
C++ Implementation

### ISSUE THREAD

**Issue by soulslicer** [AndriiHeonia/hull#7]
Your library has been the only readable and functioning Concave hull algorithm I've seen thus far. Also, it seems to run quite fast.

Currently, there is no Concave hull algorithm in C++ on the entire internet open source. Have you every thought of porting this to C++?

**Comment by AndriiHeonia** [comment]
Hello,
I agree that it would be nice to have C++ implementation, but at the moment I don't plan to do that.
